name: Manual Tournament Ranking

on:
  workflow_dispatch:   # nur manuell starten

jobs:
  run-manual:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install requests

      - name: Manual Script ausführen
        run: python scripts/manual/tournament_games_ranking.py
