name: Team World Record (Lichess)

on:
  push:
    paths:
      - "scripts/team/**"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests pytz

      - name: Run world record script
        env:
          KEY: ${{ secrets.LICHESS_TOKEN }}
        run: python scripts/team/world_record.py
